

export const project_list = [
    {
        name: "Cronômetro",
        link: "https://github.com/oThurDev/cronometro",
        html: true,
        css: true,
        js: true,
        react: false,
        desc:"Com uma interface simples e amigável, oferecemos um cronômetro digital moderno que atende às suas necessidades, seja para cronometrar atividades esportivas, controlar o tempo de estudos ou simplesmente manter o foco em suas tarefas diárias.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Jogo da Velha",
        link: "https://github.com/oThurDev/projeto-jogo-da-velha",
        html: true,
        css: true,
        js: true,
        react: false,
        desc:"Bem vindo ao projeto Jogo da Velha, seu destino online para desafios emocionantes de Jogo da Velha! Com um design intuitivo e amigável, estamos aqui para trazer diversão clássica direto para o seu navegador.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Quadro de Desenho",
        link: "https://github.com/oThurDev/projeto-quadro-de-desenho",
        html: true,
        css: true,
        js: true,
        react:false,
        desc:"O projeto Quadro de Desenho é um site inovador que oferece uma plataforma interativa para entusiastas de desenho e arte digital. Com uma interface intuitiva e amigável, os usuários podem liberar sua criatividade em um quadro de desenho digital.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Clima",
        link: "https://github.com/oThurDev/projeto-clima",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"O projeto de Clima é sua fonte completa para informações meteorológicas precisas e atualizadas. Oferecemos uma experiência simplificada para que você possa acessar facilmente dados meteorológicos essenciais.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Relógio",
        link: "https://github.com/oThurDev/projeto-relogio",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"O projeto Relógio consiste em trazer facilidade, com um design simples e fácil de usar você pode facilmente acessar a hora que quiser e não perder a hora. Temos relógio digital ou se prefirir, temos também o analógioco!",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Bateria",
        link: "https://github.com/oThurDev/projeto-bateria",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"O projeto de Bateria é a sua plataforma online dedicada ao universo das baterias musicais. Seja você um baterista profissional, entusiasta ou iniciante, oferecemos recursos abrangentes para aprimorar suas habilidades e explorar o mundo cativante da percussão.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Calculadora",
        link: "https://github.com/oThurDev/Calculadora",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"O projeto Calculadora é a sua calculadora online, simples e eficiente. Projetado para atender às suas necessidades de cálculos diários. Com funções básicas de adição, subtração, multiplicação e divisão, nossa calculadora é perfeita para tarefas rápidas e precisas.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "DevsDuo Automóveis",
        link: "https://chicoautomoveis.netlify.app/",
        html: true,
        css: true,
        js: true,
        react:  true,
        desc:"O projeto DevsDuo Automóveis é uma aplicação web em ReactJS que apresenta um catálogo de carros de uma empresa de automóveis. O site não necessita de um servidor externo e mostra de forma simples uma lista de itens.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Portfólio",
        link: "https://github.com",
        html: true,
        css: true,
        js: true,
        react:  true,
        desc:"O nosso Portfólio é a vitrine online para apresentar nosso trabalho de forma envolvente e profissional. Com um design elegante e intuitivo, o site destaca nossas habilidades, projetos e fala também um pouco sobre nós.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    }
]   