

export const project_list = [
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Massa",
        link: "https://github.com",
        html: true,
        css: false,
        js:false,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Ruim",
        link: "https://github.com",
        html: true,
        css: false,
        js:false,
        react:false,
        desc:"Esse site é ruim confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Programa Topzera",
        link: "https://github.com",
        html: true,
        css: true,
        js:true,
        react:true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
]   