

export const project_list = [
    {
        name: "Cronômetro",
        link: "https://github.com/oThurDev/cronometro",
        html: true,
        css: true,
        js: true,
        react: false,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Jogo da Velha",
        link: "https://github.com/oThurDev/projeto-jogo-da-velha",
        html: true,
        css: true,
        js: true,
        react: false,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Quadro de Desenho",
        link: "https://github.com/oThurDev/projeto-quadro-de-desenho",
        html: true,
        css: true,
        js: true,
        react:false,
        desc:"Esse site é ruim confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Clima",
        link: "https://github.com/oThurDev/projeto-clima",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Relógio",
        link: "https://github.com/oThurDev/projeto-relogio",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Bateria",
        link: "https://github.com/oThurDev/projeto-bateria",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Calculadora",
        link: "https://github.com/oThurDev/Calculadora",
        html: true,
        css: true,
        js:true,
        react: false,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Chico Automóveis",
        link: "https://github.com",
        html: true,
        css: true,
        js: true,
        react:  true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    },
    {
        name: "Portfólio",
        link: "https://github.com",
        html: true,
        css: true,
        js: true,
        react:  true,
        desc:"Esse site é top confia em nós, show de bola mesmo, Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img:"https://i.pinimg.com/originals/71/9e/80/719e80760999b4c355a723224120eb07.png",
    }
]   